name: CI

on: 
    pull_request:  
        types: 
          - opened
          - synchronize
    push:
      branches:
        - main
        - 'v**'
    merge_group: {}

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
              with:
                    fetch-depth: 0

            - name: Cache turbo build setup
              uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830  # v4
              with:
                path: .turbo
                key: ${{ runner.os }}-turbo-${{ github.sha }}
                restore-keys: |
                  ${{ runner.os }}-turbo-

            - uses: pnpm/action-setup@b906affcce14559ad1aafd4ab0e942779e9f58b1  # v4

            - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020  # v4
              with:
                node-version: 20.x
                registry-url: 'https://registry.npmjs.org'
                cache: pnpm
            
            - name: Install
              run: pnpm install

            - name: Build
              env:
                TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
                TURBO_TEAM: ${{ vars.TURBO_TEAM || github.repository_owner }}
                TURBO_REMOTE_ONLY: true
              run: pnpm build
            
            - name: Start Docker Containers
              run: |
                docker compose up -d
                # Wait for services to be ready (optional)
                sleep 10
            
            - name: Lint
              env:
                TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
                TURBO_TEAM: ${{ vars.TURBO_TEAM || github.repository_owner }}
                TURBO_REMOTE_ONLY: true
              run: pnpm lint
            
            - name: Test
              env:
                TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
                TURBO_TEAM: ${{ vars.TURBO_TEAM || github.repository_owner }}
              run: pnpm test

            - name: Typecheck
              env:
                TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
                TURBO_TEAM: ${{ vars.TURBO_TEAM || github.repository_owner }}
                TURBO_REMOTE_ONLY: true
              run: pnpm typecheck

            - name: Stop Docker Containers
              run: docker compose down
            